name: Test

# Disabled: Tests require Phoenix mock server that times out on GitHub Actions
# Root cause: test_helper.exs starts Phoenix.SocketClientTest.MockServer which hangs
# All tests are integration tests requiring WebSocket server setup
# Run tests locally with: mix test
on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Tests can take 4+ minutes to run

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18'
          otp-version: '28'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Run tests
        run: mix test --exclude performance --max-cases 1 --timeout 120000
